### ISSUE TITLE
cannot install @8080labs/gqrid

### ISSUE THREAD

**Issue by people-can-fly** [tkrabel/qgrid_jupyterlab#1]
> $ jupyter labextension install @8080labs/gqrid
> An error occured.
> ValueError: "@8080labs/gqrid" is not a valid npm package

from debug log 
> "C:\Program Files\nodejs\npm.CMD" pack @8080labs/gqrid
|npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@8080labs%2fgqrid - Not found
npm ERR! 404
npm ERR! 404  '@8080labs/gqrid@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by tkrabel** [comment]
There is a typo. The package is written @8080labs/qgrid 
Did you copy the jupyter command from somewhere?

**Comment by tkrabel** [comment]
I saw the typo in the readme. Sorry about that. Fixed it.
